name: Build PDF (LaTeX)

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - .github/workflows/latex.yml
  pull_request:
    branches: [ main ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile main.tex with latexmk
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false
          # Si algún día pasas a XeLaTeX, cambia a: latexmk_use_xelatex: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: libro-pdf
          path: main.pdf
