name: Publish PDF to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - '.github/workflows/pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF with latexmk
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false
          # Si algún día usas XeLaTeX (por fuentes CJK/OT), cambia a:
          # latexmk_use_xelatex: true

      - name: Prepare site (public/)
        run: |
          mkdir -p public
          cp main.pdf public/LibroControl.pdf
          cat > public/index.html << 'EOF'
          <!doctype html>
          <meta charset="utf-8">
          <title>LibroControl – PDF</title>
          <style>
            body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;margin:24px;line-height:1.5}
            .wrap{max-width:1100px;margin:auto}
            iframe{width:100%;height:80vh;border:1px solid #ddd;border-radius:12px}
            a.button{display:inline-block;margin:12px 0;padding:10px 16px;border:1px solid #444;border-radius:10px;text-decoration:none}
          </style>
          <div class="wrap">
            <h1>LibroControl</h1>
            <p><a class="button" href="LibroControl.pdf">⬇️ Descargar PDF</a></p>
            <iframe src="LibroControl.pdf" title="LibroControl PDF"></iframe>
          </div>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
