name: Publish PDF to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDFs (libro + capítulos + resúmenes)  # NEW
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            main.tex
            cap1_only.tex
            cap2_only.tex
            cap3_only.tex
            cap1_resumen.tex       # NEW
            cap2_resumen.tex       # NEW
            cap3_resumen.tex       # NEW
          args: -pdf -interaction=nonstopmode -file-line-error

      - name: Debug workspace
        run: |
          echo "Listando archivos en el workspace:"
          ls -la
          for f in main.pdf cap1_only.pdf cap2_only.pdf cap3_only.pdf \
                   cap1_resumen.pdf cap2_resumen.pdf cap3_resumen.pdf; do
            test -f "$f" && echo "OK: $f" || (echo "ERROR: falta $f" && exit 1)
          done

      - name: Prepare site (public/)
        run: |
          mkdir -p public
          # Renombrar PDFs con nombres amigables
          cp main.pdf             public/LibroControl.pdf
          cp cap1_only.pdf        public/Capitulo1.pdf
          cp cap2_only.pdf        public/Capitulo2.pdf
          cp cap3_only.pdf        public/Capitulo3.pdf
          cp cap1_resumen.pdf     public/Capitulo1_resumen.pdf   # NEW
          cp cap2_resumen.pdf     public/Capitulo2_resumen.pdf   # NEW
          cp cap3_resumen.pdf     public/Capitulo3_resumen.pdf   # NEW

          cat > public/index.html << 'EOF'
          <!doctype html>
          <meta charset="utf-8">
          <title>LibroControl – Publicaciones</title>
          <style>
            body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;margin:24px;line-height:1.5}
            .wrap{max-width:1100px;margin:auto}
            .row{display:flex;gap:16px;flex-wrap:wrap}
            .card{flex:1 1 320px;border:1px solid #ddd;border-radius:12px;padding:16px}
            iframe{width:100%;height:60vh;border:1px solid #ddd;border-radius:10px}
            a.button{display:inline-block;margin:8px 0;padding:8px 14px;border:1px solid #444;border-radius:10px;text-decoration:none}
            h2{margin:0 0 8px}
          </style>
          <div class="wrap">
            <h1>LibroControl – Publicaciones</h1>

            <div class="row">
              <div class="card">
                <h2>📖 Libro completo</h2>
                <a class="button" href="LibroControl.pdf?v=${GITHUB_RUN_NUMBER}">⬇️ Descargar PDF</a>
                <iframe src="LibroControl.pdf?v=${GITHUB_RUN_NUMBER}" title="Libro completo"></iframe>
              </div>

              <div class="card">
                <h2>Capítulo 1</h2>
                <a class="button" href="Capitulo1.pdf?v=${GITHUB_RUN_NUMBER}">⬇️ Descargar PDF</a>
                <iframe src="Capitulo1.pdf?v=${GITHUB_RUN_NUMBER}" title="Capítulo 1"></iframe>
                <p><a href="Capitulo1_resumen.pdf?v=${GITHUB_RUN_NUMBER}">🧭 Ver resumen</a></p> <!-- NEW -->
              </div>

              <div class="card">
                <h2>Capítulo 2</h2>
                <a class="button" href="Capitulo2.pdf?v=${GITHUB_RUN_NUMBER}">⬇️ Descargar PDF</a>
                <iframe src="Capitulo2.pdf?v=${GITHUB_RUN_NUMBER}" title="Capítulo 2"></iframe>
                <p><a href="Capitulo2_resumen.pdf?v=${GITHUB_RUN_NUMBER}">🧭 Ver resumen</a></p> <!-- NEW -->
              </div>

              <div class="card">
                <h2>Capítulo 3</h2>
                <a class="button" href="Capitulo3.pdf?v=${GITHUB_RUN_NUMBER}">⬇️ Descargar PDF</a>
                <iframe src="Capitulo3.pdf?v=${GITHUB_RUN_NUMBER}" title="Capítulo 3"></iframe>
                <p><a href="Capitulo3_resumen.pdf?v=${GITHUB_RUN_NUMBER}">🧭 Ver resumen</a></p> <!-- NEW -->
              </div>
            </div>
          </div>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
